'''
Created on May 13, 2012

@author: PENNETTI
'''
'''
Problem 2: Each new term in the Fibonacci sequence 
is generated by adding the previous two terms. By 
starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, find the 
sum of the even-valued terms.
'''
MAX = 4000000
sum = 0
i = 1

def fib(n):
    if n < 2:
        return n
    else:
        return fib(n - 1) + fib(n - 2)

while fib(i) < MAX:
    if fib(i) % 2 == 0:
        sum += fib(i)
    i += 1

print(sum)
